### ISSUE TITLE
Extracting and referencing images

### ISSUE THREAD

**Issue by RichardSieg** [emcf/thepipe#30]
I was wondering whether it is possible to extract all images from a document and reference them at their position in the generated markdown?

As I understand the documentation it should be possible but I could not get any images from PDF documents yet

> ai_extraction: Accurately extract clean markdown, cropped images, tables, and equations using a fine-tuned vision model. A 20-page PDF takes ~1 minute. (default is False)

**Comment by Prateek-coder19** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by emcf** [comment]
Hi Richard, this functionality has since changed and it looks like we never updated the documentation. My apologies for that.
If you are still looking for a solution, I recommend Vik Parachuri's [Surya](https://github.com/VikParuchuri/surya) package; it does this image extraction quite well.
