### ISSUE TITLE
No longer working after addition of THEPIPE_API_KEY

### ISSUE THREAD

**Issue by jamespet77** [emcf/thepipe#9]
I have added the env var THEPIPE_API_KEY to my .env, .bashrc and at the commandline.  It is not getting accepted. 

{response['error']}")
ValueError: Valid environment variable THEPIPE_API_KEY not found. You may need to restart if you have set your API key. Visit https://thepi.pe/docs to learn more.

**Comment by emcf** [comment]
Hi @jamespet77 , did you set `THEPIPE_API_KEY ` to your API key? If so, I'd love to get this fixed for you over our discord https://discord.gg/khsB3667 and push a change to resolve the bug.

**Comment by jamespet77** [comment]
Yes.  
I did find a workaround.
I added 

import dotenv
dotenv.load_dotenv()

to extractor.py

I am not sure why it is not picking up my env vars, but this allowed it to grab my ".env" for the project. 

If there is an alternative that is recommended, I am not seeing it in the current documentation. 
![Screenshot_20240418_112058](https://github.com/emcf/thepipe/assets/378474/65309e8c-e744-41ea-b9b1-8a81172b5921)

**Comment by emcf** [comment]
@jamespet77 Thanks! I think I understand this issue a bit better now -- a system-wide environment variable must be set (the equivalent of `export THEPIPE_API_KEY=yourkeyhere` in linux), not a .env file environment variable. I will make the readme more clear on this. It must also be valid, so if the key is invalid it will return this message.

**Comment by jamespet77** [comment]
I tried the system wide in in .bashrc and that did not work either.  Maybe it was formatted wrong??  Either way, it would be nice to have it local so that I can use a project specific KEY for it.

**Comment by emcf** [comment]
@jamespet77 I added the dotenv load as you suggested: #3fdda82 

Although, if this does not work for you, you can send me your API key at emmett@thepi.pe and I will investigate this deeper. You can also use it without an API key (see the local installation section). 

Thanks for already having spent the time to help with that workaround.
